### ISSUE TITLE
Question: how to get Thunderbolt original DROM

### ISSUE THREAD

**Issue by profzei** [whatnameisit/HP-Elite-X2-1012-G2-Hackintosh#12]
Hi,
do you know how to get original thunderbolt 3 controller drom from a laptop?
If so, please, do you have a working script or a link to a guide?

Thanks in advance for your time

**Comment by whatnameisit** [comment]
Hi. Extracting DROM is not dependent on whether you have a laptop or a desktop. If the vendor provides TB firmware via their respective update services, there you have it. If the vendor does not provide the firmware, you may use an external device to extract it.
If you don't mind me directing you to TonyShyt,
Extract TB firmware using an external device: IDK
ThunderboltUtil to extract DROM from firmware: https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.316533/page-2342#post-2148640
Half working SSDT for Alpine Ridge without proper PM: https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.316533/page-2082#post-2121513
Next time, please use the forums for generic questions.
